version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: reusable-backend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=/app/database/dev.db
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - JWT_REFRESH_SECRET=dev-refresh-secret-change-in-production
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./database:/app/database
      - ./logs:/app/logs
      - /app/node_modules
    command: npm run dev:ts
    restart: unless-stopped
    networks:
      - backend-network

  # Optional: Add Redis for caching in production
  redis:
    image: redis:7-alpine
    container_name: reusable-backend-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - backend-network
    profiles:
      - redis

  # Optional: Add monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: reusable-backend-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - backend-network
    profiles:
      - monitoring

  # Optional: Add Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: reusable-backend-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - backend-network
    profiles:
      - monitoring

networks:
  backend-network:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
  grafana-data: 