import {
  Smartphone,
  Laptop,
  Shirt,
  ShoppingBag,
  Home,
  Lamp,
  BookOpen,
  Book,
  Sparkles,
  Heart,
  Dumbbell,
  Trophy,
  Baby,
  Gamepad,
  Watch,
  Headphones,
  UtensilsCrossed,
  Apple,
  Car,
  Gauge,
  Cat,
  Fish,
  Hammer,
  Wrench,
  Flower,
  Trees,
  Speaker,
  Video,
  Gamepad2,
  Puzzle,
  Activity,
  Coffee,
  Gift,
  Tv,
  Monitor,
  Music,
  Phone,
  Pizza,
  Plane,
  Search,
  Settings,
  Share,
  Shield,
  ShoppingCart,
  Camera,
  CreditCard,
  Globe,
  Map,
  MessageCircle,
  Package,
  Sun,
  Moon,
  Star,
  Truck,
  Umbrella,
  UserCheck,
  Wifi,
  Zap,
  ThumbsUp,
  Image,
  Film,
  User,
  Users,
  BarChart,
  PieChart,
  DollarSign,
  Calendar,
  Clock,
  Award
} from "lucide-react";
import { Category } from "@/types/category";

export const iconComponents = {
  Smartphone,
  Laptop,
  Shirt, 
  ShoppingBag,
  Home,
  Lamp,
  BookOpen,
  Book,
  Sparkles,
  Heart,
  Dumbbell,
  Trophy,
  Baby,
  Gamepad,
  Watch,
  Headphones,
  UtensilsCrossed,
  Apple,
  Car,
  Gauge,
  Cat,
  Fish,
  Hammer,
  Wrench,
  Flower,
  Trees,
  Speaker,
  Video,
  Gamepad2,
  Puzzle,
  Activity,
  Coffee,
  Gift,
  Tv,
  Monitor,
  Music,
  Phone,
  Pizza,
  Plane,
  Search,
  Settings,
  Share,
  Shield,
  ShoppingCart,
  Camera,
  CreditCard,
  Globe,
  Map,
  MessageCircle,
  Package,
  Sun,
  Moon,
  Star,
  Truck,
  Umbrella,
  UserCheck,
  Wifi,
  Zap,
  ThumbsUp,
  Image,
  Film,
  User,
  Users,
  BarChart,
  PieChart,
  DollarSign,
  Calendar,
  Clock,
  Award
};

export type IconName = keyof typeof iconComponents;

export const defaultCategories: Category[] = [
  {
    id: "cat-electronics",
    name: "Eletrônicos",
    slug: "eletronicos",
    icon: "Smartphone",
    description: "Smartphones, tablets, laptops e outros dispositivos eletrônicos",
    color: "#D3E4FD",
    isDefault: true
  },
  {
    id: "cat-fashion",
    name: "Moda",
    slug: "moda",
    icon: "Shirt",
    description: "Roupas, calçados e acessórios de moda",
    color: "#FFDEE2",
    isDefault: true
  },
  {
    id: "cat-home",
    name: "Casa e Decoração",
    slug: "casa-decoracao",
    icon: "Home",
    description: "Móveis, decoração e itens para o lar",
    color: "#F2FCE2",
    isDefault: true
  },
  {
    id: "cat-books",
    name: "Livros",
    slug: "livros",
    icon: "BookOpen",
    description: "Livros físicos, e-books e audiolivros",
    color: "#FDE1D3",
    isDefault: true
  },
  {
    id: "cat-beauty",
    name: "Beleza e Saúde",
    slug: "beleza-saude",
    icon: "Sparkles",
    description: "Produtos de beleza, saúde e bem-estar",
    color: "#E5DEFF",
    isDefault: true
  },
  {
    id: "cat-sports",
    name: "Esportes",
    slug: "esportes",
    icon: "Dumbbell",
    description: "Artigos esportivos e equipamentos de fitness",
    color: "#FFCDD2",
    isDefault: true
  },
  {
    id: "cat-kids",
    name: "Infantil",
    slug: "infantil",
    icon: "Baby",
    description: "Produtos para bebês e crianças",
    color: "#FEF7CD",
    isDefault: true
  },
  {
    id: "cat-accessories",
    name: "Acessórios",
    slug: "acessorios",
    icon: "Watch",
    description: "Relógios, joias e acessórios pessoais",
    color: "#E5DEFF",
    isDefault: true
  },
  {
    id: "cat-food",
    name: "Alimentos",
    slug: "alimentos",
    icon: "UtensilsCrossed",
    description: "Alimentos, bebidas e artigos de culinária",
    color: "#F2FCE2",
    isDefault: true
  },
  {
    id: "cat-auto",
    name: "Automotivo",
    slug: "automotivo",
    icon: "Car",
    description: "Peças, acessórios e produtos para automóveis",
    color: "#D3E4FD",
    isDefault: true
  },
  {
    id: "cat-pets",
    name: "Pets",
    slug: "pets",
    icon: "Cat",
    description: "Produtos para animais de estimação",
    color: "#FDE1D3",
    isDefault: true
  },
  {
    id: "cat-tools",
    name: "Ferramentas",
    slug: "ferramentas",
    icon: "Hammer",
    description: "Ferramentas e equipamentos",
    color: "#F1F0FB",
    isDefault: true
  },
  {
    id: "cat-garden",
    name: "Jardinagem",
    slug: "jardinagem",
    icon: "Flower",
    description: "Plantas, sementes e artigos para jardim",
    color: "#F2FCE2",
    isDefault: true
  },
  {
    id: "cat-audio-video",
    name: "Áudio e Vídeo",
    slug: "audio-video",
    icon: "Speaker",
    description: "Equipamentos de áudio e vídeo",
    color: "#FFCDD2",
    isDefault: true
  },
  {
    id: "cat-games",
    name: "Jogos",
    slug: "jogos",
    icon: "Gamepad",
    description: "Jogos, consoles e acessórios para games",
    color: "#D3E4FD",
    isDefault: true
  }
];
