name: 🚨 Emergency Frontend Fix

on:
  workflow_dispatch:

jobs:
  emergency-fix:
    name: 🚨 Emergency Fix
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json

    - name: 🏗️ Build Frontend
      working-directory: ./frontend
      run: |
        npm ci --silent
        npm run build
        echo "✅ Frontend build completed"
        ls -la dist/

    - name: 📂 Copy Frontend to Backend
      run: |
        rm -rf backend/public
        cp -r frontend/dist backend/public
        echo "✅ Frontend copied to backend/public"
        ls -la backend/public/

    - name: 🚨 Emergency Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        timeout: 300s
        script: |
          echo "🚨 EMERGENCY FRONTEND FIX"
          echo "========================"
          
          # Kill all node processes
          echo "🛑 Stopping all applications..."
          pm2 delete all 2>/dev/null || echo "No PM2 processes"
          pkill -f node 2>/dev/null || echo "No node processes"
          sleep 3
          
          # Check if frontend files exist
          echo "📁 Checking frontend files..."
          ls -la /opt/fuseloja/current/backend/public/ 2>/dev/null || echo "❌ Frontend files missing!"
          
          # Create a simple test HTML if frontend is missing
          if [ ! -f "/opt/fuseloja/current/backend/public/index.html" ]; then
            echo "🔧 Creating emergency frontend..."
            mkdir -p /opt/fuseloja/current/backend/public
            cat > /opt/fuseloja/current/backend/public/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>FuseLoja - Em Manutenção</title>
              <style>
                  body { 
                      font-family: Arial, sans-serif; 
                      text-align: center; 
                      padding: 50px; 
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      margin: 0;
                  }
                  .container {
                      max-width: 600px;
                      margin: 0 auto;
                      background: rgba(255,255,255,0.1);
                      padding: 40px;
                      border-radius: 15px;
                      backdrop-filter: blur(10px);
                  }
                  h1 { font-size: 2.5em; margin-bottom: 20px; }
                  p { font-size: 1.2em; line-height: 1.6; }
                  .status { 
                      background: rgba(255,255,255,0.2); 
                      padding: 20px; 
                      border-radius: 10px; 
                      margin: 20px 0; 
                  }
                  .api-link { 
                      color: #ffd700; 
                      text-decoration: none; 
                      font-weight: bold; 
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🏪 FuseLoja</h1>
                  <p>Site em manutenção temporária</p>
                  <div class="status">
                      <p><strong>Status:</strong> Configurando frontend...</p>
                      <p><strong>Backend:</strong> ✅ Funcionando</p>
                      <p><strong>API:</strong> <a href="/api" class="api-link">Disponível</a></p>
                  </div>
                  <p>Voltaremos em breve com a experiência completa!</p>
              </div>
          </body>
          </html>
          EOF
            echo "✅ Emergency frontend created"
          fi
          
          # Navigate to backend
          cd /opt/fuseloja/current/backend
          
          # Start with minimal configuration
          echo "🚀 Starting optimized application..."
          NODE_ENV=production \
          PORT=3000 \
          pm2 start src/index.js \
            --name fuseloja-minimal \
            --instances 1 \
            --max-memory-restart 256M \
            --node-args="--max-old-space-size=256" \
            --time
          
          # Save configuration
          pm2 save
          
          echo "⏱️ Waiting for startup..."
          sleep 10
          
          # Test application
          echo "🧪 Testing application..."
          
          # Test health endpoint
          if curl -f http://localhost:3000/health > /dev/null 2>&1; then
            echo "✅ Health check: PASSED"
          else
            echo "❌ Health check: FAILED"
          fi
          
          # Test frontend
          if curl -f http://localhost:3000/ > /dev/null 2>&1; then
            echo "✅ Frontend: ACCESSIBLE"
          else
            echo "❌ Frontend: FAILED"
          fi
          
          # Test API
          if curl -f http://localhost:3000/api > /dev/null 2>&1; then
            echo "✅ API: ACCESSIBLE"
          else
            echo "❌ API: FAILED"
          fi
          
          # Show status
          echo "📊 Final status:"
          pm2 status fuseloja-minimal
          
          echo "✅ Emergency fix completed!"

    - name: 📤 Upload New Frontend Files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        source: "backend/public/*"
        target: "/opt/fuseloja/current/backend/"
        strip_components: 1

    - name: 🔄 Restart with New Frontend
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          echo "🔄 Restarting with fresh frontend..."
          
          # Verify frontend files
          ls -la /opt/fuseloja/current/backend/public/
          
          # Restart PM2
          pm2 restart fuseloja-minimal
          
          # Wait and test
          sleep 5
          
          echo "🧪 Final verification..."
          curl -I http://localhost:3000/ || echo "Test failed"
          
          echo "✅ All done! Check https://www.fuseloja.com.br"