name: 🔧 Fix Server Performance

on:
  workflow_dispatch:

jobs:
  fix-server:
    name: 🔧 Server Performance Fix
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔧 Fix Server Performance Issues
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        timeout: 300s
        script: |
          echo "🔧 FIXING SERVER PERFORMANCE"
          echo "============================"
          
          echo "🛑 Stopping problematic processes..."
          
          # Kill any hanging node processes
          pkill -f "node" || echo "No node processes to kill"
          sleep 2
          
          # Clean PM2 processes
          pm2 delete all 2>/dev/null || echo "No PM2 processes to delete"
          pm2 kill 2>/dev/null || echo "PM2 not running"
          
          echo "🧹 Cleaning up resources..."
          
          # Clear logs
          rm -rf /opt/fuseloja/logs/* 2>/dev/null || echo "No logs to clear"
          
          # Clear npm cache
          npm cache clean --force 2>/dev/null || echo "NPM cache already clean"
          
          # Free memory
          sync && echo 3 > /proc/sys/vm/drop_caches
          
          echo "🚀 Restarting application optimized..."
          
          # Navigate to app directory
          cd /opt/fuseloja/current/backend
          
          # Start with optimized PM2 configuration
          NODE_ENV=production pm2 start src/index.js \
            --name fuseloja-minimal \
            --instances 1 \
            --max-memory-restart 256M \
            --node-args="--max-old-space-size=256" \
            --log-type json \
            --merge-logs \
            --time
          
          # Save PM2 configuration
          pm2 save
          
          echo "⏱️ Waiting for startup..."
          sleep 10
          
          echo "🔍 Verifying fix..."
          
          # Check PM2 status
          pm2 status fuseloja-minimal
          
          # Test application
          echo "Testing application response..."
          for i in {1..3}; do
            echo "Attempt $i:"
            curl -w "Response time: %{time_total}s, HTTP: %{http_code}\n" \
                 -o /dev/null -s http://localhost:3000/health
            sleep 2
          done
          
          echo "✅ Performance fix completed!"
          echo "📊 Final system status:"
          free -h | grep Mem
          pm2 monit --no-interaction || pm2 status